// Generated by https://quicktype.io

export interface LoginResponse {
  token: Token;
}

export interface Token {
  authToken: string;
  refreshToken: string;
  username: string;
}

export interface LoginData {
  username: string;
  password: string;
}

export interface RegisterData {
    username:   string;
    password: string;
    passwordConfirmation:   string;
}
